# Generated by Django 4.1.5 on 2023-01-13 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0002_alter_product_productname_alter_product_productsize_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200)),
                ('ProductSize', models.CharField(max_length=200)),
                ('ProductPrice', models.IntegerField()),
                ('ProductQuantity', models.IntegerField()),
                ('NetTotal', models.IntegerField()),
            ],
        ),
    ]
