# Generated by Django 4.1.5 on 2023-01-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productapp', '0003_savedproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedproduct',
            name='VatTotal',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
